-- Create projects/chantiers table
create table if not exists projects (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  client_id bigint references clients(id) on delete cascade not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add project_id to project_photos
alter table project_photos 
add column if not exists project_id bigint references projects(id) on delete set null;

-- Add index for performance
create index if not exists idx_project_photos_project_id on project_photos(project_id);
create index if not exists idx_projects_client_id on projects(client_id);
