-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for Clients
create table clients (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  email text,
  phone text,
  address text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table clients enable row level security;

create policy "Individuals can view their own clients." on clients
  for select using (auth.uid() = user_id);

create policy "Individuals can insert their own clients." on clients
  for insert with check (auth.uid() = user_id);

create policy "Individuals can update their own clients." on clients
  for update using (auth.uid() = user_id);

create policy "Individuals can delete their own clients." on clients
  for delete using (auth.uid() = user_id);

-- Create a table for Quotes (Devis)
create table quotes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  client_id bigint references clients(id),
  client_name text, -- Denormalized for easier display if client deleted
  date date not null,
  valid_until date,
  status text default 'draft', -- draft, sent, accepted, rejected
  items jsonb, -- Storing items as JSON for simplicity in this MVP
  total_ht numeric,
  total_tva numeric,
  total_ttc numeric,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table quotes enable row level security;

create policy "Individuals can view their own quotes." on quotes
  for select using (auth.uid() = user_id);

create policy "Individuals can insert their own quotes." on quotes
  for insert with check (auth.uid() = user_id);

create policy "Individuals can update their own quotes." on quotes
  for update using (auth.uid() = user_id);

create policy "Individuals can delete their own quotes." on quotes
  for delete using (auth.uid() = user_id);

-- Create a table for Events (Agenda)
create table events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  date timestamp with time zone not null,
  time text,
  client_name text,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table events enable row level security;

create policy "Individuals can view their own events." on events
  for select using (auth.uid() = user_id);

create policy "Individuals can insert their own events." on events
  for insert with check (auth.uid() = user_id);

create policy "Individuals can update their own events." on events
  for update using (auth.uid() = user_id);

create policy "Individuals can delete their own events." on events
  for delete using (auth.uid() = user_id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
