-- Create task_tracking table for time tracking
create table if not exists task_tracking (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  quote_id bigint references quotes(id) on delete cascade,
  hours_spent numeric(10, 2) default 0,
  date date default current_date,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table task_tracking enable row level security;

create policy "Users can manage their own tracking"
  on task_tracking for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Add estimated_hours to quotes (sum of items quantity where unit is hours? OR distinct field?)
-- Better to have a simple manual override or auto-calc field.
-- Let's stick to auto-calc in frontend for now to avoid schema complexity, 
-- BUT we need a place to store the "Real" total if we want it persistent easily.
-- Actually, querying `task_tracking` sums is enough.
