
export const JOB_LIBRARIES = {
    'plombier': [
        { description: 'Tube Cuivre Ø14mm (Barre 2m)', price: 15.50, unit: 'barre', category: 'Tuyauterie' },
        { description: 'Tube Cuivre Ø16mm (Barre 2m)', price: 18.20, unit: 'barre', category: 'Tuyauterie' },
        { description: 'Tube PER Ø12mm (Couronne 100m)', price: 45.00, unit: 'couronne', category: 'Tuyauterie' },
        { description: 'Tube PER Ø16mm (Couronne 100m)', price: 55.00, unit: 'couronne', category: 'Tuyauterie' },
        { description: 'Raccord Laiton à visser 1/2"', price: 3.50, unit: 'unité', category: 'Raccords' },
        { description: 'Raccord Cuivre à souder Ø14 Coude 90°', price: 1.20, unit: 'unité', category: 'Raccords' },
        { description: 'Chauffe-eau Électrique 150L Vertical', price: 350.00, unit: 'unité', category: 'Chauffage' },
        { description: 'Chauffe-eau Électrique 200L Vertical', price: 420.00, unit: 'unité', category: 'Chauffage' },
        { description: 'Groupe de sécurité 3/4"', price: 25.00, unit: 'unité', category: 'Chauffage' },
        { description: 'Robinet flotteur WC', price: 18.00, unit: 'unité', category: 'Sanitaire' },
        { description: 'Mécanisme chasse d\'eau double poussoir', price: 35.00, unit: 'unité', category: 'Sanitaire' },
        { description: 'Mitigeur Lavabo Standard', price: 65.00, unit: 'unité', category: 'Sanitaire' },
        { description: 'Siphon Lavabo PVC', price: 8.50, unit: 'unité', category: 'Sanitaire' },
        { description: 'Forfait Recherche de Fuite', price: 120.00, unit: 'forfait', category: 'Main d\'oeuvre' },
        { description: 'Heure de main d\'oeuvre Plomberie', price: 55.00, unit: 'heure', category: 'Main d\'oeuvre' },
    ],
    'peintre': [
        { description: 'Peinture Impression Sous-couche (15L)', price: 85.00, unit: 'fut', category: 'Peinture' },
        { description: 'Peinture Acrylique Blanc Mat (15L)', price: 120.00, unit: 'fut', category: 'Peinture' },
        { description: 'Peinture Acrylique Blanc Satin (15L)', price: 135.00, unit: 'fut', category: 'Peinture' },
        { description: 'Peinture Laque Glycéro (5L)', price: 65.00, unit: 'pot', category: 'Peinture' },
        { description: 'Enduit de rebouchage (Sac 25kg)', price: 28.00, unit: 'sac', category: 'Enduits' },
        { description: 'Enduit de lissage (Saut 25kg)', price: 32.00, unit: 'seau', category: 'Enduits' },
        { description: 'Toile de verre Maille Classique (Rouleau 25m)', price: 45.00, unit: 'rouleau', category: 'Revêtement' },
        { description: 'Colle Toile de verre (Seau 10kg)', price: 30.00, unit: 'seau', category: 'Colle' },
        { description: 'Papier à poncer Grain 120', price: 0.80, unit: 'feuille', category: 'Consommable' },
        { description: 'Rouleau complet 180mm', price: 12.00, unit: 'unité', category: 'Outillage' },
        { description: 'Bache de protection (Rouleau)', price: 15.00, unit: 'rouleau', category: 'Protection' },
        { description: 'Ruban de masquage 50mm', price: 4.50, unit: 'unité', category: 'Protection' },
        { description: 'Forfait Protection Chantier', price: 50.00, unit: 'forfait', category: 'Main d\'oeuvre' },
        { description: 'Heure de main d\'oeuvre Peinture', price: 50.00, unit: 'heure', category: 'Main d\'oeuvre' },
    ],
    'electricien': [
        { description: 'Câble RO2V 3G1.5 (Couronne 100m)', price: 65.00, unit: 'couronne', category: 'Câblage' },
        { description: 'Câble RO2V 3G2.5 (Couronne 100m)', price: 95.00, unit: 'couronne', category: 'Câblage' },
        { description: 'Gaine ICTA Ø20mm (100m)', price: 25.00, unit: 'couronne', category: 'Gaines' },
        { description: 'Disjoncteur 10A Phase+Neutre', price: 12.00, unit: 'unité', category: 'Tableau' },
        { description: 'Disjoncteur 16A Phase+Neutre', price: 12.00, unit: 'unité', category: 'Tableau' },
        { description: 'Disjoncteur 20A Phase+Neutre', price: 12.00, unit: 'unité', category: 'Tableau' },
        { description: 'Interrupteur Différentiel 40A 30mA Type AC', price: 45.00, unit: 'unité', category: 'Tableau' },
        { description: 'Interrupteur Différentiel 40A 30mA Type A', price: 55.00, unit: 'unité', category: 'Tableau' },
        { description: 'Prise de courant 2P+T (Complète)', price: 15.00, unit: 'unité', category: 'Appareillage' },
        { description: 'Interrupteur Simple (Complet)', price: 14.00, unit: 'unité', category: 'Appareillage' },
        { description: 'Interrupteur Va-et-Vient (Complet)', price: 16.00, unit: 'unité', category: 'Appareillage' },
        { description: 'Boite d\'encastrement Ø67 Prof.40', price: 0.50, unit: 'unité', category: 'Appareillage' },
        { description: 'Forfait Mise en sécurité Tableau', price: 350.00, unit: 'forfait', category: 'Tableau' },
        { description: 'Heure de main d\'oeuvre Électricité', price: 60.00, unit: 'heure', category: 'Main d\'oeuvre' },
    ],
    'macon': [
        { description: 'Ciment CPJ (Sac 35kg)', price: 8.50, unit: 'sac', category: 'Matériaux' },
        { description: 'Sable à maçonner (Big Bag 1T)', price: 65.00, unit: 'bigbag', category: 'Matériaux' },
        { description: 'Mélange à béton (Big Bag 1T)', price: 70.00, unit: 'bigbag', category: 'Matériaux' },
        { description: 'Parpaing Creux 20x20x50', price: 1.80, unit: 'unité', category: 'Matériaux' },
        { description: 'Parpaing Plein 20x20x50', price: 3.50, unit: 'unité', category: 'Matériaux' },
        { description: 'Ferraillage Semelle Filante 35x15', price: 18.00, unit: 'barre', category: 'Ferraillage' },
        { description: 'Treillis Soudé PAFC', price: 25.00, unit: 'panneau', category: 'Ferraillage' },
        { description: 'Brique rouge 20x20x50', price: 2.50, unit: 'unité', category: 'Matériaux' },
        { description: 'Heure de main d\'oeuvre Maçonnerie', price: 55.00, unit: 'heure', category: 'Main d\'oeuvre' },
    ],
    'menuisier': [
        { description: 'Bloc Porte Plan Prépeint 73cm', price: 85.00, unit: 'unité', category: 'Menuiserie Int' },
        { description: 'Poignée de porte Inox', price: 25.00, unit: 'paire', category: 'Quincaillerie' },
        { description: 'Planche de Rive Sapin 20x200 (3m)', price: 18.00, unit: 'unité', category: 'Bois' },
        { description: 'Tasseau Sapin 30x40 (2.4m)', price: 4.50, unit: 'unité', category: 'Bois' },
        { description: 'Panneau OSB3 18mm 250x125', price: 35.00, unit: 'panneau', category: 'Bois' },
        { description: 'Fenêtre PVC 100x125 2 Vantaux (Standard)', price: 250.00, unit: 'unité', category: 'Menuiserie Ext' },
        { description: 'Baie Vitrée Alu 215x240 (Standard)', price: 800.00, unit: 'unité', category: 'Menuiserie Ext' },
        { description: 'Heure de main d\'oeuvre Menuiserie', price: 55.00, unit: 'heure', category: 'Main d\'oeuvre' },
    ],
    'paysagiste': [
        { description: 'Terreau Universel (Sac 50L)', price: 12.00, unit: 'sac', category: 'Plantation' },
        { description: 'Gazon Roulé (m2)', price: 8.00, unit: 'm2', category: 'Gazon' },
        { description: 'Semence Gazon Rustique (Sac 10kg)', price: 45.00, unit: 'sac', category: 'Gazon' },
        { description: 'Taille de haie (ml)', price: 15.00, unit: 'ml', category: 'Entretien' },
        { description: 'Tonte de pelouse (m2)', price: 0.50, unit: 'm2', category: 'Entretien' },
        { description: 'Evacuation déchets verts (m3)', price: 45.00, unit: 'm3', category: 'Entretien' },
        { description: 'Paillage Ecorce de Pin (Sac 50L)', price: 14.00, unit: 'sac', category: 'Plantation' },
        { description: 'Heure de main d\'oeuvre Paysagiste', price: 50.00, unit: 'heure', category: 'Main d\'oeuvre' },
    ],
    'chauffagiste': [
        { description: 'Chaudière Gas Condensation 25kW', price: 1800.00, unit: 'unité', category: 'Chauffage' },
        { description: 'Pompe à Chaleur Air/Eau 8kW', price: 6500.00, unit: 'unité', category: 'Chauffage' },
        { description: 'Radiateur Acier Blanc HT600 Type 22 (1000W)', price: 150.00, unit: 'unité', category: 'Emetteur' },
        { description: 'Thermostat Connecté', price: 180.00, unit: 'unité', category: 'Régulation' },
        { description: 'Entretien Annuel Chaudière Gaz', price: 120.00, unit: 'forfait', category: 'Maintenance' },
        { description: 'Désembouage Radiateurs (jusqu\'à 8)', price: 450.00, unit: 'forfait', category: 'Maintenance' },
        { description: 'Tube Cuivre Ø14mm (Barre 2m)', price: 15.50, unit: 'barre', category: 'Tuyauterie' },
        { description: 'Heure de main d\'oeuvre Chauffagiste', price: 60.00, unit: 'heure', category: 'Main d\'oeuvre' }
    ],
    'carreleur': [
        { description: 'Carrelage Grès Cérame 60x60 (m2)', price: 25.00, unit: 'm2', category: 'Revêtement' },
        { description: 'Faïence Murale 20x40 (m2)', price: 20.00, unit: 'm2', category: 'Revêtement' },
        { description: 'Colle Flex (Sac 25kg)', price: 28.00, unit: 'sac', category: 'Consommable' },
        { description: 'Joint Carrelage Gris (Sac 5kg)', price: 12.00, unit: 'sac', category: 'Consommable' },
        { description: 'Ragréage Sol (Sac 25kg)', price: 30.00, unit: 'sac', category: 'Préparation' },
        { description: 'Primaire d\'accrochage (5L)', price: 45.00, unit: 'bidon', category: 'Préparation' },
        { description: 'Pose Carrelage Sol (m2)', price: 45.00, unit: 'm2', category: 'Main d\'oeuvre' },
        { description: 'Pose Faïence (m2)', price: 50.00, unit: 'm2', category: 'Main d\'oeuvre' },
        { description: 'Heure de main d\'oeuvre Carreleur', price: 50.00, unit: 'heure', category: 'Main d\'oeuvre' }
    ],
    'plaquiste': [
        { description: 'Plaque BA13 Standard 250x120', price: 9.50, unit: 'unité', category: 'Plaques' },
        { description: 'Plaque BA13 Hydrofuge 250x120', price: 16.50, unit: 'unité', category: 'Plaques' },
        { description: 'Plaque BA13 Phonique 250x120', price: 18.00, unit: 'unité', category: 'Plaques' },
        { description: 'Montant M48 (3m)', price: 4.80, unit: 'unité', category: 'Ossature' },
        { description: 'Rail R48 (3m)', price: 4.50, unit: 'unité', category: 'Ossature' },
        { description: 'Vis Placo 35mm (Boite 1000)', price: 15.00, unit: 'boite', category: 'Consommable' },
        { description: 'Bande à joint papier (150m)', price: 6.00, unit: 'rouleau', category: 'Consommable' },
        { description: 'Enduit Joint Prise Rapide (25kg)', price: 25.00, unit: 'sac', category: 'Consommable' },
        { description: 'Laine de Verre 45mm (Rouleau 15m2)', price: 45.00, unit: 'rouleau', category: 'Isolation' },
        { description: 'Heure de main d\'oeuvre Plaquiste', price: 50.00, unit: 'heure', category: 'Main d\'oeuvre' }
    ],
    'charpentier': [
        { description: 'Bastaing Sapin 63x175 (4m)', price: 28.00, unit: 'unité', category: 'Bois' },
        { description: 'Madrier Sapin 75x225 (4m)', price: 45.00, unit: 'unité', category: 'Bois' },
        { description: 'Chevron Traité 60x80 (4m)', price: 12.00, unit: 'unité', category: 'Bois' },
        { description: 'Volige 15x150 (Planoc)', price: 9.00, unit: 'm2', category: 'Bois' },
        { description: 'Liteau 27x40 (ml)', price: 0.80, unit: 'ml', category: 'Bois' },
        { description: 'Tuile Mécanique Rouge', price: 1.50, unit: 'unité', category: 'Couverture' },
        { description: 'Écran Sous-Toiture (Rouleau 75m2)', price: 120.00, unit: 'rouleau', category: 'Couverture' },
        { description: 'Sabot de charpente galva', price: 5.50, unit: 'unité', category: 'Quincaillerie' },
        { description: 'Heure de main d\'oeuvre Charpentier', price: 55.00, unit: 'heure', category: 'Main d\'oeuvre' }
    ],
    'multiservice': [
        { description: 'Heure de main d\'oeuvre', price: 45.00, unit: 'heure', category: 'Main d\'oeuvre' },
        { description: 'Forfait Déplacement', price: 40.00, unit: 'forfait', category: 'Déplacement' },
        { description: 'Petit Matériel Divers', price: 15.00, unit: 'forfait', category: 'Fournitures' },
        { description: 'Montage Meuble Kit (Heure)', price: 45.00, unit: 'heure', category: 'Montage' },
        { description: 'Remplacement Joint Silicone (ml)', price: 12.00, unit: 'ml', category: 'Plomberie' },
        { description: 'Remplacement Ampoule / Néon', price: 10.00, unit: 'unité', category: 'Electricité' },
        { description: 'Fixation Tringle Rideau', price: 35.00, unit: 'unité', category: 'Bricolage' },
    ]
};
