-- Create project_photos table
create table if not exists project_photos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  client_id bigint references clients(id) on delete cascade,
  photo_url text not null,
  category text not null check (category in ('before', 'during', 'after')),
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table project_photos enable row level security;

-- RLS Policies
create policy "Users can view their own project photos"
  on project_photos for select
  using (auth.uid() = user_id);

create policy "Users can insert their own project photos"
  on project_photos for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own project photos"
  on project_photos for delete
  using (auth.uid() = user_id);

-- Create Storage Bucket for Project Photos
insert into storage.buckets (id, name, public)
values ('project-photos', 'project-photos', true)
on conflict (id) do nothing;

-- Storage Policies
create policy "Project photos are publicly accessible"
  on storage.objects for select
  using ( bucket_id = 'project-photos' );

create policy "Users can upload project photos"
  on storage.objects for insert
  with check (
    bucket_id = 'project-photos' AND
    auth.uid() = owner
  );

create policy "Users can delete their own project photos"
  on storage.objects for delete
  using (
    bucket_id = 'project-photos' AND
    auth.uid() = owner
  );
