// Fonctions SECURITY DEFINER qui ne doivent plus être appelables par un
// visiteur (clé anon) ni, pour les helpers de trigger, par un artisan connecté.
// On charge les migrations d'origine puis le verrouillage, dans un vrai
// PostgreSQL (PGlite), et on vérifie deux choses : l'appel direct est refusé,
// et les triggers qui s'en servent continuent de fonctionner.

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { cwd } from 'node:process';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { PGlite } from '@electric-sql/pglite';

const mig = (name) => readFileSync(path.join(cwd(), 'supabase/migrations', name), 'utf8');

const USER_A = '11111111-1111-1111-1111-111111111111';
const USER_B = '22222222-2222-2222-2222-222222222222';

// auth.uid() lit le « sub » du JWT comme le fait Supabase.
const SCHEMA = `
CREATE ROLE anon;
CREATE ROLE authenticated;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
  $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
GRANT USAGE ON SCHEMA auth TO anon, authenticated;

CREATE TABLE quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  client_id bigint,
  status text DEFAULT 'draft',
  title text, notes text, items jsonb,
  total_ht numeric, total_tva numeric, total_ttc numeric,
  date date DEFAULT CURRENT_DATE, valid_until date,
  include_tva boolean, has_material_deposit boolean,
  token_expires_at timestamptz, token_revoked boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE ON quotes TO authenticated;

CREATE TABLE usage_tracking (
  user_id uuid, month text,
  voice_memos_count integer DEFAULT 0,
  ai_generations_count integer DEFAULT 0,
  updated_at timestamptz,
  UNIQUE (user_id, month)
);

-- Version d'origine (fix_security_vulnerabilities.sql), jamais versionnée.
CREATE FUNCTION cleanup_expired_tokens() RETURNS integer LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE n integer;
BEGIN
  UPDATE quotes SET token_revoked = TRUE
   WHERE token_expires_at < NOW() - INTERVAL '7 days' AND NOT token_revoked;
  GET DIAGNOSTICS n = ROW_COUNT;
  RETURN n;
END $$;
`;

let db;

const as = async (role, sub, sql, params = []) => {
    await db.exec(`SET ROLE ${role}`);
    await db.query(`SELECT set_config('request.jwt.claim.sub', $1, false)`, [sub ?? '']);
    try {
        return await db.query(sql, params);
    } finally {
        await db.exec('RESET ROLE');
    }
};

beforeAll(async () => {
    db = await PGlite.create();
    await db.exec(SCHEMA);
    await db.exec(mig('20260312120000_add_usage_rpc.sql'));
    await db.exec(mig('20260317110000_per_user_quote_numbering.sql'));
    await db.exec(mig('20260610100000_quote_versions_archive.sql'));
    await db.exec(mig('20260928140000_lock_down_definer_rpcs.sql'));
});

afterAll(async () => {
    await db?.close();
});

describe('helpers de trigger : plus appelables directement', () => {
    it.each(['anon', 'authenticated'])('insert_quote_version refusée à %s', async (role) => {
        await expect(
            as(role, USER_A, `SELECT insert_quote_version(NULL::quotes, 'sent')`)
        ).rejects.toThrow(/permission denied for function/);
    });

    it.each(['anon', 'authenticated'])('get_next_quote_number refusée à %s', async (role) => {
        await expect(as(role, USER_A, 'SELECT get_next_quote_number($1)', [USER_B])).rejects.toThrow(
            /permission denied for function/
        );
    });

    it.each(['anon', 'authenticated'])('cleanup_expired_tokens refusée à %s', async (role) => {
        await expect(as(role, null, 'SELECT cleanup_expired_tokens()')).rejects.toThrow(/permission denied for function/);
    });
});

describe('les triggers qui les utilisent fonctionnent toujours', () => {
    it('numérote un nouveau devis (assign_quote_number → get_next_quote_number)', async () => {
        const { rows } = await as(
            'authenticated',
            USER_A,
            `INSERT INTO quotes (user_id, status, title) VALUES ($1, 'draft', 'Tableau') RETURNING quote_number`,
            [USER_A]
        );
        expect(rows[0].quote_number).toBe(1);
    });

    it('archive la version envoyée (archive_quote_version → insert_quote_version)', async () => {
        await as('authenticated', USER_A, `UPDATE quotes SET status = 'sent' WHERE user_id = $1`, [USER_A]);
        const { rows } = await db.query('SELECT reason, user_id FROM quote_versions');
        expect(rows).toEqual([{ reason: 'sent', user_id: USER_A }]);
    });

    it('le ménage nocturne tourne toujours en tant que propriétaire (pg_cron)', async () => {
        const { rows } = await db.query('SELECT cleanup_expired_tokens() AS n');
        expect(rows[0].n).toBe(0);
    });
});

describe('compteurs d’usage : seulement le sien', () => {
    const count = async (user) =>
        (await db.query('SELECT ai_generations_count, voice_memos_count FROM usage_tracking WHERE user_id = $1', [user]))
            .rows[0];

    it.each(['increment_ai_generation_usage', 'increment_voice_memo_usage'])(
        '%s refuse de gonfler le compteur d’un autre artisan',
        async (fn) => {
            await expect(
                as('authenticated', USER_A, `SELECT ${fn}($1, '2026-09')`, [USER_B])
            ).rejects.toThrow(/forbidden/);
            expect(await count(USER_B)).toBeUndefined();
        }
    );

    it.each(['increment_ai_generation_usage', 'increment_voice_memo_usage'])(
        '%s refusée à anon',
        async (fn) => {
            await expect(as('anon', null, `SELECT ${fn}($1, '2026-09')`, [USER_A])).rejects.toThrow(
                /permission denied for function/
            );
        }
    );

    it('incrémente le compteur de l’utilisateur connecté (ai-proxy, voice-transcribe)', async () => {
        await as('authenticated', USER_A, `SELECT increment_ai_generation_usage($1, '2026-09')`, [USER_A]);
        await as('authenticated', USER_A, `SELECT increment_ai_generation_usage($1, '2026-09')`, [USER_A]);
        await as('authenticated', USER_A, `SELECT increment_voice_memo_usage($1, '2026-09')`, [USER_A]);
        expect(await count(USER_A)).toEqual({ ai_generations_count: 2, voice_memos_count: 1 });
    });
});
