// Conformité de la numérotation des factures (art. 242 nonies A, ann. II CGI) :
// la migration est chargée dans un PostgreSQL en mémoire et on vérifie que la
// série FAC-AAAA-NNNN est continue, chronologique, unique, attribuée à
// l'émission uniquement, et qu'une facture émise est immuable (ni suppression,
// ni retour en devis, ni changement de numéro).

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { cwd } from 'node:process';
import { beforeAll, afterAll, describe, expect, it } from 'vitest';
import { PGlite } from '@electric-sql/pglite';

const MIG = path.join(cwd(), 'supabase/migrations/20260822130000_invoice_numbering_compliance.sql');

// La migration redéfinit aussi get_public_quote, dont les dépendances (tables
// du portail, client_facing_items…) n'existent pas ici : plpgsql ne vérifie
// que la syntaxe à la création, la fonction est donc chargeable sans elles.
const SCHEMA = `
CREATE SCHEMA auth;
CREATE TABLE auth.users (id uuid PRIMARY KEY);
CREATE ROLE anon;
CREATE ROLE authenticated;
CREATE TABLE quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  type text DEFAULT 'quote',
  status text DEFAULT 'draft',
  quote_number integer,
  is_external boolean DEFAULT false,
  date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz NOT NULL DEFAULT now()
);
`;

const USER_A = '11111111-1111-1111-1111-111111111111';
const USER_B = '22222222-2222-2222-2222-222222222222';

let db;

const invoiceNumberOf = async (id) => {
    const { rows } = await db.query('SELECT invoice_number FROM quotes WHERE id = $1', [id]);
    return rows[0]?.invoice_number ?? null;
};

beforeAll(async () => {
    db = await PGlite.create();
    await db.exec(SCHEMA);
    await db.query('INSERT INTO auth.users (id) VALUES ($1), ($2)', [USER_A, USER_B]);

    // Historique AVANT migration : mélange devis / factures sur deux années,
    // avec un brouillon et un document externe qui ne doivent pas être repris.
    await db.query(
        `INSERT INTO quotes (id, user_id, type, status, quote_number, is_external, date, created_at) VALUES
         (1, $1, 'quote',   'sent',   1, false, '2025-03-01', '2025-03-01'),
         (2, $1, 'invoice', 'paid',   2, false, '2025-06-15', '2025-06-15'),
         (3, $1, 'invoice', 'billed', 3, false, '2025-02-10', '2025-02-10'),
         (4, $1, 'invoice', 'billed', 4, false, '2026-01-20', '2026-01-20'),
         (5, $1, 'invoice', 'draft',  5, false, '2026-02-01', '2026-02-01'),
         (6, $1, 'invoice', 'billed', 6, true,  '2026-02-05', '2026-02-05'),
         (7, $2, 'invoice', 'billed', 1, false, '2026-03-01', '2026-03-01')`,
        [USER_A, USER_B],
    );

    await db.exec(readFileSync(MIG, 'utf8'));
});

afterAll(async () => {
    await db?.close();
});

describe('reprise de l’existant (backfill)', () => {
    it('numérote les factures émises par ordre chronologique, par année et par utilisateur', async () => {
        // 2025 : la facture du 10/02 précède celle du 15/06, quel que soit quote_number.
        expect(await invoiceNumberOf(3)).toBe('FAC-2025-0001');
        expect(await invoiceNumberOf(2)).toBe('FAC-2025-0002');
        expect(await invoiceNumberOf(4)).toBe('FAC-2026-0001');
        // Série indépendante pour l'autre utilisateur.
        expect(await invoiceNumberOf(7)).toBe('FAC-2026-0001');
    });

    it('ne numérote ni les devis, ni les brouillons, ni les documents externes', async () => {
        expect(await invoiceNumberOf(1)).toBeNull();
        expect(await invoiceNumberOf(5)).toBeNull();
        expect(await invoiceNumberOf(6)).toBeNull();
    });

    it('initialise les compteurs à la suite de la reprise', async () => {
        const { rows } = await db.query(
            'SELECT year, last_number FROM invoice_counters WHERE user_id = $1 ORDER BY year',
            [USER_A],
        );
        expect(rows).toEqual([
            { year: 2025, last_number: 2 },
            { year: 2026, last_number: 1 },
        ]);
    });
});

describe('émission', () => {
    it('attribue le numéro suivant à l’insertion d’une facture hors brouillon', async () => {
        await db.query(
            `INSERT INTO quotes (id, user_id, type, status, date) VALUES (10, $1, 'invoice', 'billed', '2026-04-01')`,
            [USER_A],
        );
        expect(await invoiceNumberOf(10)).toBe('FAC-2026-0002');
    });

    it('n’attribue rien à un brouillon, puis numérote à son émission', async () => {
        await db.query(
            `INSERT INTO quotes (id, user_id, type, status, date) VALUES (11, $1, 'invoice', 'draft', '2026-04-02')`,
            [USER_A],
        );
        expect(await invoiceNumberOf(11)).toBeNull();

        await db.query(`UPDATE quotes SET status = 'sent' WHERE id = 11`);
        expect(await invoiceNumberOf(11)).toBe('FAC-2026-0003');
    });

    it('numérote un devis au moment de sa conversion en facture', async () => {
        await db.query(
            `INSERT INTO quotes (id, user_id, type, status, quote_number, date) VALUES (12, $1, 'quote', 'accepted', 99, '2026-04-03')`,
            [USER_A],
        );
        expect(await invoiceNumberOf(12)).toBeNull();

        await db.query(`UPDATE quotes SET type = 'invoice' WHERE id = 12`);
        expect(await invoiceNumberOf(12)).toBe('FAC-2026-0004');
    });

    it('ne numérote jamais un document externe', async () => {
        await db.query(
            `INSERT INTO quotes (id, user_id, type, status, is_external, date) VALUES (13, $1, 'invoice', 'billed', true, '2026-04-04')`,
            [USER_A],
        );
        expect(await invoiceNumberOf(13)).toBeNull();
    });
});

describe('immuabilité d’une facture émise', () => {
    it('refuse la suppression (il faut un avoir)', async () => {
        await expect(db.query('DELETE FROM quotes WHERE id = 10')).rejects.toThrow(/interdit sa suppression/);
    });

    it('autorise la suppression d’un devis ou d’un brouillon de facture jamais émis', async () => {
        await db.query(
            `INSERT INTO quotes (id, user_id, type, status, date) VALUES (14, $1, 'invoice', 'draft', '2026-04-05'), (15, $1, 'quote', 'sent', '2026-04-05')`,
            [USER_A],
        );
        await db.query('DELETE FROM quotes WHERE id IN (14, 15)');
        const { rows } = await db.query('SELECT count(*)::int AS n FROM quotes WHERE id IN (14, 15)');
        expect(rows[0].n).toBe(0);
    });

    it('refuse le retour en devis', async () => {
        await expect(db.query(`UPDATE quotes SET type = 'quote' WHERE id = 10`)).rejects.toThrow(/redevenir un devis/);
    });

    it('fige le numéro : une tentative de modification est ignorée', async () => {
        await db.query(`UPDATE quotes SET invoice_number = 'FAUX-999' WHERE id = 10`);
        expect(await invoiceNumberOf(10)).toBe('FAC-2026-0002');

        await db.query(`UPDATE quotes SET invoice_number = NULL WHERE id = 10`);
        expect(await invoiceNumberOf(10)).toBe('FAC-2026-0002');
    });

    it('le numéro survit à un repassage du statut en brouillon', async () => {
        await db.query(`UPDATE quotes SET status = 'draft' WHERE id = 11`);
        expect(await invoiceNumberOf(11)).toBe('FAC-2026-0003');
    });
});

describe('unicité', () => {
    it('rejette un doublon de numéro pour un même utilisateur', async () => {
        await expect(db.query(
            `INSERT INTO quotes (id, user_id, type, status, invoice_number, date)
             VALUES (16, $1, 'invoice', 'billed', 'FAC-2026-0002', '2026-04-06')`,
            [USER_A],
        )).rejects.toThrow(/quotes_user_invoice_number_key|duplicate/i);
    });
});
