// Rapprochement des commandes fournisseurs avec les chantiers, dans un vrai
// PostgreSQL (PGlite) : on charge la migration et on vérifie que le prix payé
// arrive sur la bonne ligne « à commander », qu'un artisan ne peut pas viser
// le devis d'un autre, et que les RPC restent fermées à la clé anon.

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { cwd } from 'node:process';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { PGlite } from '@electric-sql/pglite';

const mig = (name) => readFileSync(path.join(cwd(), 'supabase/migrations', name), 'utf8');

const USER_A = '11111111-1111-1111-1111-111111111111';
const USER_B = '22222222-2222-2222-2222-222222222222';

const SCHEMA = `
CREATE ROLE anon;
CREATE ROLE authenticated;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
  $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
GRANT USAGE ON SCHEMA auth TO anon, authenticated;

CREATE TABLE quotes (
  id bigint PRIMARY KEY, user_id uuid NOT NULL, client_id bigint, client_name text,
  title text, status text, type text DEFAULT 'quote', parent_quote_id bigint,
  include_tva boolean DEFAULT true, items jsonb, total_ht numeric, date date DEFAULT CURRENT_DATE
);
CREATE TABLE procurement_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid NOT NULL,
  client_id bigint, quote_id bigint REFERENCES quotes(id), site_label text, description text,
  quantity numeric DEFAULT 1, unit text, category text, status text DEFAULT 'pending',
  ordered_at timestamptz, source text, sale_price numeric, buying_price numeric,
  supplier text, notes text, created_at timestamptz DEFAULT now()
);
CREATE TABLE task_tracking (quote_id bigint, hours_spent numeric);
CREATE TABLE supplier_invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid NOT NULL,
  supplier_name text, invoice_date date, total_ttc numeric,
  source text NOT NULL DEFAULT 'upload' CHECK (source IN ('upload', 'manual'))
);
CREATE TABLE supplier_purchases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid NOT NULL,
  invoice_id bigint REFERENCES supplier_invoices(id), supplier_name text,
  product_name text NOT NULL, product_key text NOT NULL, reference text,
  quantity numeric DEFAULT 1, unit text DEFAULT 'u', unit_price numeric, total_price numeric,
  purchase_date date
);
GRANT SELECT, INSERT, UPDATE ON quotes, procurement_items, supplier_invoices, supplier_purchases TO authenticated;

INSERT INTO quotes (id, user_id, client_id, client_name, title, status, include_tva) VALUES
  (1, '${USER_A}', 10, 'Dupont', 'Tableau Dupont', 'accepted', false),
  (2, '${USER_A}', 10, 'Dupont', 'Avenant', 'accepted', false),
  (3, '${USER_B}', 20, 'Secret', 'Chantier confidentiel', 'accepted', true);
UPDATE quotes SET parent_quote_id = 1, type = 'amendment' WHERE id = 2;
`;

// Après la migration (elle ajoute la colonne reference).
const SEED = `
INSERT INTO procurement_items (id, user_id, quote_id, description, reference, quantity, buying_price) VALUES
  (100, '${USER_A}', 1, 'Disjoncteur 16A', '406774', 9, 6.5);
`;

let db;

const as = async (role, sub, sql, params = []) => {
    await db.exec(`SET ROLE ${role}`);
    await db.query(`SELECT set_config('request.jwt.claim.sub', $1, false)`, [sub ?? '']);
    try {
        return await db.query(sql, params);
    } finally {
        await db.exec('RESET ROLE');
    }
};

const insertPurchase = (user, fields) => {
    const cols = Object.keys(fields);
    const vals = cols.map((_, i) => `$${i + 1}`);
    return as('authenticated', user,
        `INSERT INTO supplier_purchases (${cols.join(', ')}) VALUES (${vals.join(', ')})
         RETURNING id, quote_id, procurement_item_id, match_status`,
        Object.values(fields));
};

beforeAll(async () => {
    db = await PGlite.create();
    await db.exec(SCHEMA);
    await db.exec(mig('20261005120000_supplier_orders_matching.sql'));
    await db.exec(SEED);
});

afterAll(async () => {
    await db?.close();
});

describe('match_supplier_purchase', () => {
    it('règle la ligne prévue du devis au prix TTC payé (franchise de TVA)', async () => {
        const { rows } = await insertPurchase(USER_A, {
            user_id: USER_A, product_name: 'Disj. DNX 1P+N 16A LEG406774', product_key: 'disj',
            reference: 'LEG406774', quantity: 9, unit_price: 6, unit_price_ttc: 7.2,
            origin: 'web_order', quote_id: 1,
        });
        expect(rows[0]).toMatchObject({ procurement_item_id: 100, match_status: 'auto', quote_id: 1 });
        const item = (await db.query('SELECT buying_price, buying_price_source, status FROM procurement_items WHERE id = 100')).rows[0];
        expect(Number(item.buying_price)).toBe(7.2);
        expect(item).toMatchObject({ buying_price_source: 'web_order', status: 'ordered' });
    });

    it('remonte un avenant au devis parent et crée la ligne d’achat', async () => {
        const { rows } = await insertPurchase(USER_A, {
            user_id: USER_A, product_name: 'Gaine ICTA 20', product_key: 'gaine',
            quantity: 1, unit_price: 25, unit_price_ttc: 30, origin: 'web_order', quote_id: 2,
        });
        expect(rows[0]).toMatchObject({ quote_id: 1, match_status: 'created' });
        const item = (await db.query('SELECT quote_id, buying_price FROM procurement_items WHERE id = $1', [rows[0].procurement_item_id])).rows[0];
        expect(item.quote_id).toBe(1);
        expect(Number(item.buying_price)).toBe(30);
    });

    it('ignore le devis d’un autre artisan (rien n’est recopié)', async () => {
        const { rows } = await insertPurchase(USER_A, {
            user_id: USER_A, product_name: 'Hublot', product_key: 'hublot',
            quantity: 1, unit_price: 10, origin: 'web_order', quote_id: 3,
        });
        expect(rows[0]).toMatchObject({ quote_id: null, match_status: 'unmatched', procurement_item_id: null });
        const leaked = await db.query(`SELECT 1 FROM procurement_items WHERE site_label = 'Chantier confidentiel'`);
        expect(leaked.rows).toHaveLength(0);
    });

    it('laisse passer une ligne « manual » puis la RPC la relie', async () => {
        await db.query(`INSERT INTO procurement_items (id, user_id, quote_id, description, quantity, buying_price) VALUES (101, $1, 1, 'Interrupteur différentiel', 1, 40)`, [USER_A]);
        const { rows } = await insertPurchase(USER_A, {
            user_id: USER_A, product_name: 'ID 40A type A', product_key: 'id',
            quantity: 1, unit_price: 45, unit_price_ttc: 54, origin: 'web_order', quote_id: 1, match_status: 'manual',
        });
        expect(rows[0]).toMatchObject({ match_status: 'manual', procurement_item_id: null });
        await as('authenticated', USER_A, 'SELECT link_supplier_purchase($1, 101)', [rows[0].id]);
        const item = (await db.query('SELECT buying_price FROM procurement_items WHERE id = 101')).rows[0];
        expect(Number(item.buying_price)).toBe(54);
    });

    it('ne réécrit pas le prix d’une ligne déjà réglée quand on rachète la même référence', async () => {
        await db.query(`INSERT INTO procurement_items (id, user_id, quote_id, description, reference, quantity) VALUES (102, $1, 1, 'Peigne 1P', '404926', 6)`, [USER_A]);
        const first = await insertPurchase(USER_A, {
            user_id: USER_A, product_name: 'Peigne 404926', product_key: 'peigne', reference: '404926',
            quantity: 6, unit_price: 2.33, unit_price_ttc: 2.8, origin: 'web_order', quote_id: 1,
        });
        expect(first.rows[0]).toMatchObject({ procurement_item_id: 102, match_status: 'auto' });
        const again = await insertPurchase(USER_A, {
            user_id: USER_A, product_name: 'Peigne 404926', product_key: 'peigne', reference: '404926',
            quantity: 10, unit_price: 2.49, unit_price_ttc: 2.99, origin: 'web_order',
        });
        expect(again.rows[0]).toMatchObject({ procurement_item_id: null, match_status: 'unmatched' });
        const item = (await db.query('SELECT buying_price FROM procurement_items WHERE id = 102')).rows[0];
        expect(Number(item.buying_price)).toBe(2.8);
    });

    it('laisse la facture remplacer le prix de la commande web', async () => {
        const { rows } = await insertPurchase(USER_A, {
            user_id: USER_A, product_name: 'Peigne 404926', product_key: 'peigne', reference: '404926',
            quantity: 6, unit_price: 2.25, unit_price_ttc: 2.7, origin: 'invoice',
        });
        expect(rows[0]).toMatchObject({ procurement_item_id: 102, match_status: 'auto' });
        const item = (await db.query('SELECT buying_price, buying_price_source FROM procurement_items WHERE id = 102')).rows[0];
        expect(item).toMatchObject({ buying_price_source: 'invoice' });
        expect(Number(item.buying_price)).toBe(2.7);
    });
});

describe('RPC de rattachement', () => {
    it.each([
        ['link_supplier_purchase', 'SELECT link_supplier_purchase(1, 1)'],
        ['ignore_supplier_purchase', 'SELECT ignore_supplier_purchase(1)'],
        ['attach_supplier_purchase_to_quote', 'SELECT attach_supplier_purchase_to_quote(1, 1)'],
    ])('%s refusée à anon', async (_, sql) => {
        await expect(as('anon', null, sql)).rejects.toThrow(/permission denied for function/);
    });

    it('attach refuse le devis d’un autre artisan', async () => {
        const { rows } = await insertPurchase(USER_A, {
            user_id: USER_A, product_name: 'Spot', product_key: 'spot', quantity: 1, unit_price: 5, origin: 'invoice',
        });
        await expect(
            as('authenticated', USER_A, 'SELECT attach_supplier_purchase_to_quote($1, 3)', [rows[0].id])
        ).rejects.toThrow(/introuvable/);
        const id = (await as('authenticated', USER_A, 'SELECT attach_supplier_purchase_to_quote($1, 1) AS id', [rows[0].id])).rows[0].id;
        expect(id).toBeTruthy();
    });
});

describe('quote_margins', () => {
    it('donne la marge matière réelle du chantier racine', async () => {
        const { rows } = await db.query('SELECT quote_id, material_real_cost, item_real_count FROM quote_margins WHERE quote_id = 1');
        expect(rows).toHaveLength(1);
        expect(Number(rows[0].material_real_cost)).toBeGreaterThan(0);
    });
});
