// La migration « objet des travaux » ajoute une colonne ET redéfinit
// get_public_quote (140 lignes reprises de la migration précédente). Une faute
// de frappe dans cette reprise ne se verrait qu'au déploiement : on charge donc
// la vraie migration dans un PostgreSQL en mémoire pour la valider.
//
// Les dépendances de la fonction (client_facing_items, quote_views…) n'existent
// pas ici : plpgsql ne vérifie que la syntaxe à la création, la fonction est
// donc chargeable sans elles.

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { cwd } from 'node:process';
import { beforeAll, afterAll, describe, expect, it } from 'vitest';
import { PGlite } from '@electric-sql/pglite';

const MIG = path.join(cwd(), 'supabase/migrations/20260823120000_add_work_object_to_quotes.sql');

const SCHEMA = `
CREATE TABLE quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  title text
);
`;

let db;

beforeAll(async () => {
    db = await PGlite.create();
    await db.exec(SCHEMA);
    await db.exec(readFileSync(MIG, 'utf8'));
});

afterAll(async () => {
    await db?.close();
});

describe('migration objet des travaux', () => {
    it('ajoute la colonne work_object sur quotes', async () => {
        const { rows } = await db.query(
            `SELECT data_type FROM information_schema.columns
             WHERE table_name = 'quotes' AND column_name = 'work_object'`
        );
        expect(rows).toHaveLength(1);
        expect(rows[0].data_type).toBe('text');
    });

    it('est rejouable sans erreur (add column if not exists)', async () => {
        await expect(db.exec(readFileSync(MIG, 'utf8'))).resolves.toBeDefined();
    });

    it('redéfinit get_public_quote en exposant work_object au client final', async () => {
        const { rows } = await db.query(
            `SELECT prosrc FROM pg_proc WHERE proname = 'get_public_quote'`
        );
        expect(rows).toHaveLength(1);
        // La clé est exposée dans le JSON renvoyé au lien public…
        expect(rows[0].prosrc).toContain("'work_object', q.work_object");
        // …sans perdre ce que la définition précédente exposait déjà.
        ['title', 'invoice_number', 'notes', 'content_en', 'amendment_details'].forEach((key) => {
            expect(rows[0].prosrc).toContain(`'${key}', q.${key}`);
        });
    });
});
