-- Suivi de chantier ligne par ligne depuis le mode terrain.
--
-- Une ligne par (artisan, devis) : les cases cochées et les travaux constatés
-- hors devis. Stocké en JSONB plutôt qu'en lignes séparées parce que le suivi
-- est toujours lu et écrit en bloc (un chantier à la fois), et parce que les
-- clés référencent des lignes du JSON `quotes.items` — sans table à joindre.
--
--   done   : { "line:12": "2026-07-27T09:12:00Z", "comp:12:3": "..." }
--            clé de ligne → horodatage de la coche.
--   extras : [{ id, description, quantity, unit, created_at, updated_at }]
--            travaux faits sur place mais absents du devis (futur avenant).

create table if not exists chantier_progress (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    quote_id bigint references quotes(id) on delete cascade not null,
    done jsonb not null default '{}'::jsonb,
    extras jsonb not null default '[]'::jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique (user_id, quote_id)
);

create index if not exists idx_chantier_progress_quote_id on chantier_progress(quote_id);

alter table chantier_progress enable row level security;

-- Le suivi est une donnée interne à l'artisan : ni le client ni le portail n'y accèdent.
drop policy if exists "Users can manage their own chantier progress" on chantier_progress;
create policy "Users can manage their own chantier progress"
    on chantier_progress for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
