-- Pointage des heures : la fonctionnalité « Heures & rentabilité » s'appuie
-- sur la table task_tracking (une ligne par pointage). Cette migration la
-- crée si besoin (elle vivait dans un script racine hors chaîne de
-- migrations) et ajoute les index nécessaires à la feuille d'heures
-- (utilisateur + date) et à la rentabilité par chantier (devis).

create table if not exists task_tracking (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  quote_id bigint references quotes(id) on delete cascade,
  hours_spent numeric(10, 2) default 0,
  date date default current_date,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table task_tracking enable row level security;

drop policy if exists "Users can manage their own tracking" on task_tracking;
create policy "Users can manage their own tracking"
  on task_tracking for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists idx_task_tracking_user_date on task_tracking(user_id, date);
create index if not exists idx_task_tracking_quote_id on task_tracking(quote_id);
